name: Test coverage 
on: [push, pull_request]
jobs:
  test-coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - run: yarn install
      - run: yarn build
      - run: yarn install
      - run: yarn coverage
